-- Buat user baru => PERPUSTAKAAN

-- Buat 3 table baru
CREATE TABLE "PERPUSTAKAAN"."MAHASISWA" (
  "ID" INT NOT NULL,
  "NAMA" VARCHAR2(255),
  "NRP" VARCHAR2(50),
  "ANGKATAN" VARCHAR2(4),
  "KELAS" VARCHAR2(255),
  "NO_TELP" VARCHAR2(50),
  PRIMARY KEY ("ID")
)

CREATE TABLE "PERPUSTAKAAN"."BUKU" (
  "ID" INT NOT NULL,
  "JUDUL" VARCHAR2(255),
  "PENULIS" VARCHAR2(255),
  "PENERBIT" VARCHAR2(255),
  "TAHUN_TERBIT" VARCHAR2(4),
  "ISBN" VARCHAR2(100),
  "NO_BUKU" VARCHAR2(50),
  PRIMARY KEY ("ID")
)

CREATE TABLE "PERPUSTAKAAN"."TRANSAKSI" (
  "ID" INT NOT NULL,
  "BUKU_ID" INT NOT NULL,
  "MAHASISWA_ID" INT NOT NULL,
  "WAKTU_PINJAM" DATE,
  "WAKTU_KEMBALI" DATE,
  PRIMARY KEY ("ID"),
  CONSTRAINT "BUKU_ID" FOREIGN KEY ("BUKU_ID") REFERENCES "PERPUSTAKAAN"."BUKU" ("ID") ON DELETE CASCADE,
  CONSTRAINT "MAHASISWA_ID" FOREIGN KEY ("MAHASISWA_ID") REFERENCES "PERPUSTAKAAN"."MAHASISWA" ("ID") ON DELETE CASCADE
)

-- Buat trigger untuk auto increment ID
CREATE TRIGGER "PERPUSTAKAAN"."ADD_NEW_MAHASISWA" 
BEFORE INSERT ON "PERPUSTAKAAN"."MAHASISWA" 
FOR EACH ROW 
DECLARE
	m_id INTEGER;
BEGIN
  SELECT MAX(ID) INTO m_id 
	FROM MAHASISWA;
	
	:new.id := m_id + 1;
END;

CREATE TRIGGER "PERPUSTAKAAN"."ADD_NEW_BUKU" 
BEFORE INSERT ON "PERPUSTAKAAN"."BUKU" 
FOR EACH ROW 
DECLARE
	b_id INTEGER;
BEGIN
  SELECT MAX(ID) INTO b_id 
	FROM BUKU;
	
	:new.id := b_id + 1;
END;

CREATE TRIGGER "PERPUSTAKAAN"."ADD_NEW_TRANSAKSI" 
BEFORE INSERT ON "PERPUSTAKAAN"."TRANSAKSI" 
FOR EACH ROW 
DECLARE
	t_id INTEGER;
BEGIN
  SELECT MAX(ID) INTO t_id 
	FROM TRANSAKSI;
	
	:new.id := t_id + 1;
END;

-- QUERY TAMBAHAN MUNGKIN

CREATE SEQUENCE "PERPUSTAKAAN"."MAHASISWA_SEQ"START WITH 1;

CREATE TRIGGER "PERPUSTAKAAN"."ADD_NEW_BUKU" 
BEFORE INSERT ON "PERPUSTAKAAN"."BUKU" 
FOR EACH ROW 

BEGIN
  SELECT buku_seq.NEXTVAL
  INTO  :new.id 
	FROM dual;
END;