<?php

$getTransaksi = "SELECT 
                 PERPUSTAKAAN.TRANSAKSI.ID, 
                  PERPUSTAKAAN.TRANSAKSI.WAKTU_PINJAM,
                  PERPUSTAKAAN.TRANSAKSI.WAKTU_KEMBALI, 
                  PERPUSTAKAAN.BUKU.JUDUL, 
                  PERPUSTAKAAN.MAHASISWA.NAMA, 
                  PERPUSTAKAAN.MAHASISWA.NRP
                 FROM PERPUSTAKAAN.TRANSAKSI 
                 INNER JOIN 
                  PERPUSTAKAAN.BUKU ON 
                  PERPUSTAKAAN.TRANSAKSI.BUKU_ID = PERPUSTAKAAN.BUKU.ID
                 INNER JOIN 
                  PERPUSTAKAAN.MAHASISWA ON 
                  PERPUSTAKAAN.TRANSAKSI.MAHASISWA_ID = PERPUSTAKAAN.MAHASISWA.ID
                 ORDER BY PERPUSTAKAAN.TRANSAKSI.WAKTU_PINJAM DESC";

$getBukuOption = "SELECT PERPUSTAKAAN.BUKU.ID, PERPUSTAKAAN.BUKU.JUDUL
                  FROM PERPUSTAKAAN.BUKU
                  ORDER BY PERPUSTAKAAN.BUKU.JUDUL ASC";

$getMahasiswaOption = "SELECT PERPUSTAKAAN.MAHASISWA.ID, PERPUSTAKAAN.MAHASISWA.NAMA
                       FROM PERPUSTAKAAN.MAHASISWA
                       ORDER BY PERPUSTAKAAN.MAHASISWA.NAMA ASC";